### ISSUE TITLE
Default DockerFile

### ISSUE THREAD

**Issue by carloshenriqueribeiro** [blogifierdotnet/Blogifier#104]
It is a suggestion:

This project could have a standard dockerfile.

What do you think of this ?

**Comment by green16** [comment]
I'm have Dockerfile, but he not startup:
An assembly specified in the application dependencies manifest (Blogifier.Web.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

**Comment by mosakashaka** [comment]
My simple Dockerfile
```
FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
ARG appdir=Blogifier

# Copy everything else and build
COPY $appdir/ ./
RUN dotnet restore

RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/src/App/out .
COPY --from=build-env /app/plugins/Common/out/ .
COPY --from=build-env /app/src/Upgrade/out/ .
ENTRYPOINT ["dotnet", "App.dll"]

```
Blogifier is the directory for the project.
Also I think some changes should be made to `appsettings`  so that the database and uploaded images could be persisted through docker volume or other means.

**Comment by inickolayev** [comment]
Hi! I cloned the project and added dockerfile and docker-compose file by visual studio. And for blog it works fine, but for admin part I have a strange exception:
```
2020-08-21 21:52:40.389 +00:00 [Warning] Unhandled exception rendering component: "Could not find 'commonJsFunctions' in 'window'.
Error: Could not find 'commonJsFunctions' in 'window'.
    at http://localhost:6020/_framework/blazor.server.js:8:30944
    at Array.forEach (<anonymous>)
    at p (http://localhost:6020/_framework/blazor.server.js:8:30904)
    at http://localhost:6020/_framework/blazor.server.js:8:31614
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:6020/_framework/blazor.server.js:8:31587)
    at http://localhost:6020/_framework/blazor.server.js:1:20052
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:6020/_framework/blazor.server.js:1:20022)
    at e.processIncomingData (http://localhost:6020/_framework/blazor.server.js:1:18006)"
```
And blazor closes connection, if it throws. May be I need to change docker files?
Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["src/Blogifier/Blogifier.csproj", "src/Blogifier/"]
COPY ["src/Blogifier.Widgets/Blogifier.Widgets.csproj", "src/Blogifier.Widgets/"]
COPY ["src/Blogifier.Core/Blogifier.Core.csproj", "src/Blogifier.Core/"]
RUN dotnet restore "src/Blogifier/Blogifier.csproj"
COPY . .
WORKDIR "/src/src/Blogifier"
RUN dotnet build "Blogifier.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Blogifier.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Blogifier.dll"]
```
docker-compose.yml
```
version: '3.4'

services:
  blogifier:
    image: ${DOCKER_REGISTRY-}blogifier
    build:
      context: .
      dockerfile: src/Blogifier/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6020:80"
```

**Comment by farzindev** [comment]
Blogifier has changed a lot.
Also, Dockerfile added as well.
