### ISSUE TITLE
Publishing v2.3 from Visual Studio failing

### ISSUE THREAD

**Issue by cesar-younes** [blogifierdotnet/Blogifier#129]
I pulled a copy of v2.3. I published the App project through right-click publish from Visual Studio to a newly created Azure Web App. I added an SqlServer as the data source and I can confirm that it works because migrations executed and the database was populated. When I load the default landing page it's blank and the logs show the error below. I don't know dotnet core well enough to get to the bottom of this, do you know what might be causing this?

System.InvalidOperationException: A view component named 'HtmlBlock' could not be found. A view component must be a public non-abstract class, not contain any generic parameters, and either be decorated with 'ViewComponentAttribute' or have a class name ending with the 'ViewComponent' suffix. A view component must not be decorated with 'NonViewComponentAttribute'.
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeAsync(String name, Object arguments)
   at AspNetCore.Views_Themes_Standard__Shared__Header.ExecuteAsync() in D:\home\site\wwwroot\Views\Themes\Standard\_Shared\_Header.cshtml:line 11
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore.Views_Themes_Standard_List.<>c__DisplayClass19_0.<<ExecuteAsync>b__1>d.MoveNext()

**Comment by cesar-younes** [comment]
Update: I uploaded Common.dll manually to where App.dll is hosted and now it works
