### ISSUE TITLE
Use MySQL instead of SQLite, and throw ArgumentException

### ISSUE THREAD

**Issue by forconz** [blogifierdotnet/Blogifier#76]
By default, Blogifier uses SQLite. Now, I Use MySQL instead of SQLite.

I use Pomelo.EntityFrameworkCore.MySql for accessing a MySQL database using Entity Framework.
I install Pomelo.EntityFrameworkCore.MySql into Blogifier.Web.csproj and Blogifier.Core.csproj by NuGet.
Pomelo.EntityFrameworkCore.MySql
Pomelo.EntityFrameworkCore.MySql.Design

open appsettings.json configuration file:

"ConnectionStrings": {
  "DefaultConnection": "DataSource=Data\\app.db"
},
"Blogifier": {
  "InitializeDatabase": true
}

First, Modify connection string
change value of "DefaultConnection" to point to MySql.
For example:
host=localhost;port=3306;user id=root;password=123456;database=blog;

Second, 

update Startup.cs to use MySQL. From:

options.UseSqlite(Configuration.GetConnectionString("DefaultConnection"));

To:
options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));

**System.ArgumentException:“An item with the same key has already been added. Key: Microsoft.EntityFrameworkCore.Infrastructure.Internal.MySqlOptionsExtension”**

($exception).StackTrace

   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.EntityFrameworkCore.DbContextOptions`1.WithExtension[TExtension](TExtension extension)
   at Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsBuilderInfrastructure.AddOrUpdateExtension[TExtension](TExtension extension)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.ConfigureWarnings(DbContextOptionsBuilder optionsBuilder)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 mySqlOptionsAction)
   at Blogifier.Startup.<ConfigureServices>b__4_0(DbContextOptionsBuilder options) in C:\Users\lenovo\Downloads\Blogifier-master\Blogifier-master\Blogifier.Web\Startup.cs:line 34
   at Blogifier.Core.Data.BlogifierDbContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Users\lenovo\Downloads\Blogifier-master\Blogifier-master\Blogifier.Core\Data\BlogifierDbContext.cs:line 24
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Blogifier.Core.Middleware.AppSettingsLoader..ctor(RequestDelegate next, IConfiguration config) in C:\Users\lenovo\Downloads\Blogifier-master\Blogifier-master\Blogifier.Core\Middleware\AppSettingsLoader.cs:line 25

**Comment by forconz** [comment]
aspnetroleclaims
aspnetroles
aspnetuserclaims
aspnetuserlogins
aspnetuserroles
aspnetusers
aspnetusertokens
__efmigrationshistory
these table where created, there are no more other tables.

The table such as Asset,BlogPost,Category,CustomField,PostCategory,Profile are missing.

**Comment by forconz** [comment]
\Blogifier-master\Blogifier-master\Blogifier.Core\Data\BlogifierDbContext.cs:line 24 

I remove some code, it worked ok.

        //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //{
        //    //ApplicationSettings.DatabaseOptions(optionsBuilder);
        //    base.OnConfiguring(optionsBuilder);
        //}

**Comment by forconz** [comment]
but when I view a blog detail, I get a InvalidOperationException:

System.InvalidOperationException:“No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.”

   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Blogifier.Core.Services.Routing.AuthorRouteConstraint.Match(HttpContext httpContext, IRouter route, String routeKey, RouteValueDictionary values, RouteDirection routeDirection) in C:\Users\lenovo\Downloads\Blogifier-master\Blogifier-master\Blogifier.Core\Services\Routing\AuthorRouteConstraint.cs:line 18
   at Microsoft.AspNetCore.Routing.RouteConstraintMatcher.Match(IDictionary`2 constraints, RouteValueDictionary routeValues, HttpContext httpContext, IRouter route, RouteDirection routeDirection, ILogger logger)
   at Microsoft.AspNetCore.Routing.Tree.TreeRouter.<RouteAsync>d__13.MoveNext()

**Comment by forconz** [comment]
removed codes:
//var _context = new BlogifierDbContext(new DbContextOptions<BlogifierDbContext>());

and add codes to \Blogifier-master\Blogifier-master\Blogifier.Core\Services\Routing\AuthorRouteConstraint.cs

                var builder = new DbContextOptionsBuilder<BlogifierDbContext>();
                ApplicationSettings.DatabaseOptions(builder);
                DbContextOptions<BlogifierDbContext> options = builder.Options;

added codes to replace removed codes.

it is work ok.

because new DbContextOptions<BlogifierDbContext>() is new instance, it have not connection string, so it throw System.InvalidOperationException:No database provider has been configured for this DbContext.

ApplicationSettings.DatabaseOptions is static object, contains DbContextOptions.

**Comment by liuyl1992** [comment]
me too

**Comment by forconz** [comment]
#76
